name: Test CI

on:
  push:
    branches:
      - '**'
  pull_request:
    types:
      - opened
      - reopened

jobs:
 lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Run linting
        run: npm run lint
